syntax = "proto3";

package product;

service ProductService {
  rpc GetVariantDetails (GetVariantDetailsRequest) returns (GetVariantDetailsResponse);

  rpc ReserveStock (ReserveStockRequest) returns (ReserveStockResponse);

  rpc ReleaseReservedStock (ReleaseReservedStockRequest) returns (ReleaseReservedStockResponse);
}

message GetVariantDetailsRequest {
  string variantId = 1;
}

message GetVariantDetailsResponse {
  bool success = 1;
  Variant variant = 2;
  string message = 3;
  Error error = 4;
}

message Variant {
  string id = 1;
  string productId = 2;
  string sku = 3;
  map<string, string> options = 4;
  Price price = 5;
  int32 stock = 6;
  string baseUnit = 7;
  repeated VariantImage variantImages = 8;
  bool isActive = 9;
}

message Price {
  double amount = 1;
  string currency = 2;
}

message VariantImage {
  string url = 1;
  string altText = 2;
  string fileId = 3;
}

message ReserveStockRequest {
  string variantId = 1;
  int32 quantity = 2;
  string reservationId = 3;
}
message ReserveStockResponse {
  bool success = 1;
  string reserveId = 2;
  string message = 3;
  Error error = 4;
}

message ReleaseReservedStockRequest {
  string reserveId = 1;
  string reservationId = 2;
}

message ReleaseReservedStockResponse {
  bool success = 1;
  string message = 2;
  Error error = 3;
}

message Error {
  string code = 1;
  string message = 2;
  repeated string details = 3;
}
